In [15]:
import numpy as np
import pandas as pd

In [16]:
def set_long(row):
    ''' Creates a function that returns the proper longitude for each
    station ID. 
    
    @param row = iterates over each row of the dataset 
    
    ----------
    >>>>>>>>> 
    ''' 
    if row["Stn Id"] == 159:
        return -117.9858
    elif row['Stn Id'] == 78:
        return -117.81307
    elif row['Stn Id'] == 256:
        return -117.991997
    elif row['Stn Id'] == 99:
        return -118.47689
    elif row['Stn Id'] == 174:
        return -118.09479
    elif row['Stn Id'] == 197:
        return -118.03249
    elif row['Stn Id'] == 204:
        return -118.51758
    elif row['Stn Id'] == 220:
        return -118.1275
    else:
        return 100

In [17]:
def set_lat(row):
     ''' Creates a function that returns the proper latitude for each
    station ID. 
    
    @param row = iterates over each row of the dataset 
    
    ----------
    >>>>>>>>> 
    ''' 
    if row["Stn Id"] == 159:
        return 34.146372
    elif row['Stn Id'] == 78:
        return 34.056589
    elif row['Stn Id'] == 256:
        return 34.759475
    elif row['Stn Id'] == 99:
        return 34.044311
    elif row['Stn Id'] == 174:
        return 33.798697
    elif row['Stn Id'] == 197:
        return 34.614981
    elif row['Stn Id'] == 204:
        return 34.426361
    elif row['Stn Id'] == 220:
        return 34.592222
    else:
        return 100

In [34]:
def prepdataformapping(filename):
    ''' Return data ready for mapping by adding latitude and longitude
    Loads in csv ignoring rows with too many or too few columns
    Selects data by night time hours only
    Assigns lat and longitude based on functions set_lat and set_long
    .assign creates new column name
    .apply axis = 1 sends each row to the function set_***
    
    Exports csv file with name 'mapping filename'
    
    @param filename = n-dimensional array of values from CIMIS data csv
    
    ----------
    >>>>>>>>> 
    ''' 
    data = pd.read_csv(filename, error_bad_lines=False)
    datadark = data.loc[data['Hour (PST)'].isin([2000,2100,2200,2300,2400,100,200,300,400,500])]
    datadark = datadark.assign(lat=datadark.apply(set_lat, axis=1))
    datadark = datadark.assign(long=datadark.apply(set_long, axis=1))
    datadark.to_csv('mapping {}'.format(filename))

In [35]:
prepdataformapping('LAJan2020.csv')

In [21]:
datadark

,Stn Id,Stn Name,CIMIS Region,Date,Hour (PST),Jul,ETo (in),Precip (in),Sol Rad (Ly/day),Vap Pres (mBars),Air Temp (F),Rel Hum (%),Dew Point (F),Wind Speed (mph),Wind Dir (0-360),Soil Temp (F),lat,long
0,78,Pomona,Los Angeles Basin,1/1/2020,100,1,0.0,0.0,0,6.4,49.7,52,33.0,3.1,55,50.1,34.056589,-117.813070
1,78,Pomona,Los Angeles Basin,1/1/2020,200,1,0.0,0.0,0,6.4,47.2,58,33.3,1.8,27,50.0,34.056589,-117.813070
2,78,Pomona,Los Angeles Basin,1/1/2020,300,1,0.0,0.0,0,8.4,44.5,84,40.1,1.2,58,49.9,34.056589,-117.813070
3,78,Pomona,Los Angeles Basin,1/1/2020,400,1,0.0,0.0,0,7.0,43.3,73,35.4,2.5,30,49.7,34.056589,-117.813070
4,78,Pomona,Los Angeles Basin,1/1/2020,500,1,0.0,0.0,0,6.7,45.3,65,34.2,3.2,15,49.7,34.056589,-117.813070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4641,256,Lancaster,Los Angeles Basin,1/31/2020,2000,31,0.0,0.0,0,8.6,50.5,69,40.6,5.1,181,48.8,34.759475,-117.991997
4642,256,Lancaster,Los Angeles Basin,1/31/2020,2100,31,0.0,0.0,0,8.0,47.9,70,38.7,4.2,173,48.9,34.759475,-117.991997
4643,256,Lancaster,Los Angeles Basin,1/31/2020,2200,31,0.0,0.0,0,12.0,53.0,88,49.4,4.3,164,48.7,34.759475,-117.991997
4644,256,Lancaster,Los Angeles Basin,1/31/2020,2300,31,0.0,0.0,0,10.3,48.6,89,45.4,4.2,158,48.5,34.759475,-117.991997
4645,256,Lancaster,Los Angeles Basin,1/31/2020,2400,31,0.0,0.0,0,7.8,43.4,81,38.1,2.5,151,48.2,34.759475,-117.991997

In [7]:
datadark = datadark.assign(sum=datadark['Hour (PST)'].cumsum())

In [11]:
datadark.to_csv(r'Jan2020latlong')

In [8]:
datadark

,Stn Id,Stn Name,CIMIS Region,Date,Hour (PST),Jul,ETo (in),Precip (in),Sol Rad (Ly/day),Vap Pres (mBars),Air Temp (F),Rel Hum (%),Dew Point (F),Wind Speed (mph),Wind Dir (0-360),Soil Temp (F),lat,long,sum
0,78,Pomona,Los Angeles Basin,1/1/2020,100,1,0.0,0.0,0,6.4,49.7,52,33.0,3.1,55,50.1,34.056589,-117.813070,100
1,78,Pomona,Los Angeles Basin,1/1/2020,200,1,0.0,0.0,0,6.4,47.2,58,33.3,1.8,27,50.0,34.056589,-117.813070,300
2,78,Pomona,Los Angeles Basin,1/1/2020,300,1,0.0,0.0,0,8.4,44.5,84,40.1,1.2,58,49.9,34.056589,-117.813070,600
3,78,Pomona,Los Angeles Basin,1/1/2020,400,1,0.0,0.0,0,7.0,43.3,73,35.4,2.5,30,49.7,34.056589,-117.813070,1000
4,78,Pomona,Los Angeles Basin,1/1/2020,500,1,0.0,0.0,0,6.7,45.3,65,34.2,3.2,15,49.7,34.056589,-117.813070,1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4641,256,Lancaster,Los Angeles Basin,1/31/2020,2000,31,0.0,0.0,0,8.6,50.5,69,40.6,5.1,181,48.8,34.759475,-117.991997,2311100
4642,256,Lancaster,Los Angeles Basin,1/31/2020,2100,31,0.0,0.0,0,8.0,47.9,70,38.7,4.2,173,48.9,34.759475,-117.991997,2313200
4643,256,Lancaster,Los Angeles Basin,1/31/2020,2200,31,0.0,0.0,0,12.0,53.0,88,49.4,4.3,164,48.7,34.759475,-117.991997,2315400
4644,256,Lancaster,Los Angeles Basin,1/31/2020,2300,31,0.0,0.0,0,10.3,48.6,89,45.4,4.2,158,48.5,34.759475,-117.991997,2317700
4645,256,Lancaster,Los Angeles Basin,1/31/2020,2400,31,0.0,0.0,0,7.8,43.4,81,38.1,2.5,151,48.2,34.759475,-117.991997,2320100

In [ ]:
def dataformapping(filename, stationID):
    ''' Return plots of temp over time.
    First loads in data, error_bad_lines = False ignores bad lines, parse_dates combines date and hour columns into single column
    Second selects only data referring to stationID
    Creates two subsets from above using sol radiance > 0 or =0
    finally plots first using a empty fig, leaving in third plot for future
    Want to add in third plot of soil vs air temp
    
    @param filename = n-dimensional array of values
    @param stationID = stationID of location of interest
    
    Examples
    ----------
    >>>>>>>>> 
    ''' 
    data = pd.read_csv(filename, error_bad_lines=False)
    specificcity = data.loc[data['Stn Id'] == stationID]
    specificcitylighttemps = specificcity.loc[specificcity['Sol Rad (Ly/day)'] > 0]
    specificcitydarktemps = specificcity.loc[specificcity['Sol Rad (Ly/day)'] == 0]
    specificcitydarktemps['difference'] = specificcitydarktemps['Air Temp (F)'] - specificcitydarktemps['Soil Temp (F)']
    warnings.simplefilter(action = 'ignore', category = FutureWarning) #ignorning future warning not sure what it is
    fig = plt.figure(figsize = (10.0, 3.0))
    axes1 = fig.add_subplot(1,3,1) 
    axes2 = fig.add_subplot(1,3,2)
    axes3 = fig.add_subplot(1,3,3)
    axes1.plot(specificcitylighttemps['Date_Hour (PST)'], specificcitylighttemps['Air Temp (F)'])
    axes2.plot(specificcitydarktemps['Date_Hour (PST)'], specificcitydarktemps['Air Temp (F)'])
    axes3.plot(specificcitydarktemps['Date_Hour (PST)'], specificcitydarktemps['difference'])
    plt.show()